apiVersion: apps/v1 # the api we want to ue for deployment 
kind: Deployment # the kind of object we want to create

metadata:
  name: nginx-deploy # naming the deployment
spec:
  selector:
    matchLabels:
      app: nginx #  look for this label to match with k8 service
  replicas: 1 # Create replicas of this with instances/pods

  template:
    metadata:
      labels:
        app: nginx # This label connects to the service
    # Lets define another container spec
    spec:
      containers:
      - name: nginx
        image: iwparry/tech201-nginx:latest 
        ports:
        - containerPort: 80
---

apiVersion: v1 # the api we want to use for service
kind: Service

metadata:
  name: nginx-svc

spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001 # range 30000-32768
  
  selector:
    app: nginx # this label connects this service to deployment
